/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login into an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["login"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["authResponse"];
                    };
                };
                /** @description Unathorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description structure of the register */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["register"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["authResponse"];
                    };
                };
                /** @description Created */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all expenses */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    minAmount?: number;
                    maxAmount?: number;
                    currency?: string;
                    transactionType?: "expense" | "income";
                    fromDate?: string;
                    toDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expense"][];
                    };
                };
            };
        };
        put?: never;
        /** Add an expense */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description structure of the expense */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["expenseCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expense"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an expense entry by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Numeric ID of the expense to get */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expense"];
                    };
                };
            };
        };
        /** Update an expense */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Numeric ID of the expense to update */
                    id: number;
                };
                cookie?: never;
            };
            /** @description structure of the expense */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["expenseUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["expense"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an expense */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Numeric ID of the expense to delete */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        authResponse: {
            token: string;
            user: {
                id: number;
                username: string;
                firstName: string;
                lastName: string;
            };
        };
        expense: {
            id: number;
            category: string;
            amount: number;
            currency: string;
            description: string;
            /** @enum {string} */
            transactionType: "income" | "expense";
            /** Format: date */
            recordedAt: string;
        };
        expenseCreate: {
            category: string;
            amount: number;
            currency: string;
            description: string;
            /** @enum {string} */
            transactionType: "income" | "expense";
            /** Format: date */
            recordedAt: string;
        };
        expenseUpdate: {
            category?: string;
            amount?: number;
            currency?: string;
            description?: string;
            /** @enum {string} */
            transactionType?: "income" | "expense";
            /** Format: date */
            recordedAt?: string;
        };
        login: {
            username: string;
            password: string;
        };
        register: {
            username: string;
            password: string;
            firstName: string;
            lastName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
